[OPENJDK-2837] Suitably rename the test
rh-openjdk/redhat-openjdk-containers pull request #480
Opened 2024-04-10 14:24 UTC by jhuttana

Could you please take a look?

2024-04-12 09:11 UTC, jmtd commented
Please include a link to the relevant JIRA issue in all PRs (I've edited it into this one).

The referenced issue is for UBI9 but this issue is targetting UBI8.

What's the  motivation for renaming the file? Please include that in the commit message.

2024-04-12 09:12 UTC, jmtd requested changes
pls see previous comment

2024-04-12 11:17 UTC, jhuttana commented
> Please include a link to the relevant JIRA issue in all PRs (I've edited it into this one).
Actually I don't have JIRA tracker specific to this. 
The suitable one I found is [OPENJDK-2722](https://issues.redhat.com/browse/OPENJDK-2722) so adding that to the title.
> 
> The referenced issue is for UBI9 but this issue is targetting UBI8.

Sorry that was misleading.

> 
> What's the motivation for renaming the file? Please include that in the commit message.

Sure I will add that

2024-04-15 07:32 UTC, jmtd approved these changes

2024-04-15 07:32 UTC, merged