[OPENJDK-2916] Reintroduce Pathfinder module
rh-openjdk/redhat-openjdk-containers pull request #482
Opened 2024-04-12 17:25 UTC by Josh-Matsuoka

This PR combines https://github.com/jboss-container-images/openjdk/pull/401 and https://github.com/jboss-container-images/openjdk/pull/455 and reintroduces the pathfinder module, targeting the ubi9 branch since we were unable to isolate the commits and cherry pick it over, a new PR was the cleanest way forward.

2024-04-15 06:13 UTC, jhuttana reviewed
LGTM
I have verified the build for JDK 21 and I can see the jlink related script placed under expected path
```
$ docker run --rm -ti ubi9/openjdk-21:latest bash -c "ls -l /opt/jboss/container/java/jlink"
total 16
-rwxrwxr--. 1 default root  313 Apr 15 05:44 generatejdkdeps.sh
-rwxrwxr--. 1 default root 1082 Apr 15 05:44 mkdeps.sh
-rwxrwxr--. 1 default root  322 Apr 15 05:44 mkjreimage.sh
-rwxrwxr--. 1 default root  612 Apr 15 05:44 mkstrippeddeps.sh
```

2024-04-15 07:57 UTC, jmtd commented on modules/jdk/11/module.yaml
> +  - java-11-openjdk-jmods
We don't want the jmods RPMs in the release builder images, please remove this line and the equivalent one in JDK17 module.

2024-04-15 07:58 UTC, jmtd commented on modules/s2i/bash/artifacts/usr/local/s2i/assemble
> +# run the pathfinder scripts to define JAVA_APP_JAR and JAVA_LIB_DIR
we don't need these changes (yet), please let's leave them for the jlink-dev PR.

2024-04-15 07:59 UTC, jmtd commented on modules/s2i/bash/module.yaml
> +  - name: jboss.container.java.jlink
please remove reference to jlink module here

2024-04-15 07:59 UTC, jmtd commented on modules/s2i/core/artifacts/opt/jboss/container/s2i/core/s2i-core
> +  S2I_ENABLE_JLINK="${S2I_ENABLE_JLINK:-false}"
drop the changes to this file from this PR

2024-04-15 08:24 UTC, jmtd commented on modules/util/pathfinder/artifacts/opt/jboss/container/util/pathfinder/pathfinder.sh
> +  # Check also $JAVA_APP_DIR. Overrides other defaults
This is the code from run-java.sh prior to merging https://github.com/jboss-container-images/openjdk/pull/478 -- please update the pathfinder copy in this PR to reflect the latest logic in the ubi9 branch

2024-04-15 08:26 UTC, jmtd commented on modules/util/pathfinder/module.yaml
> +- name: JAVA_APP_DIR
please also remove the documentation for these three environment variables from the old location in `modules/run/module.yaml`.

2024-04-15 08:29 UTC, jmtd requested changes
A few changes to make please, the main ones being remove the jlink module and references to it (we want to save that for the final PR that merges the jlink-dev branch in) and update the pathfinder logic to reflect the current logic in the ubi9 branch, which has moved on a bit from what it was when you originally created pathfinder.

2024-04-16 10:10 UTC, jmtd commented on modules/s2i/bash/module.yaml
> +  - name: jboss.container.util.pathfinder
This isn't needed until we introduce the jlink module; please remove

2024-04-16 10:11 UTC, jmtd commented on modules/jlink/artifacts/opt/jboss/container/java/jlink/generatejdkdeps.sh
> +#!/bin/bash
Please drop all the files matching `modules/jlink/*` from this PR

2024-04-16 10:11 UTC, jmtd commented on modules/s2i/core/module.yaml
> +- name: S2I_ENABLE_JLINK
Please drop this

2024-04-16 10:12 UTC, jmtd requested changes
Thanks for iterating fast on this Josh. A couple more issues to resolve.

2024-04-17 07:44 UTC, jmtd requested changes
PLease remove these remaining jlink module files:
`modules/jlink/artifacts/opt/jboss/container/java/jlink/generatejdkdeps.sh`
`modules/jlink/artifacts/opt/jboss/container/java/jlink/mkdeps.sh`
`modules/jlink/artifacts/opt/jboss/container/java/jlink/mkjreimage.sh`
`modules/jlink/artifacts/opt/jboss/container/java/jlink/mkstrippeddeps.sh`
`modules/jlink/configure.sh`
`modules/jlink/module.yaml`

2024-04-25 11:09 UTC, jmtd commented
We should revisit the approach to this. Merging this in isolation from jlink-dev carries no advantages to the images but introduces the risk of a bug (however small).

2024-04-25 11:09 UTC, closed without merging